//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_SistemaIntranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apoderado
    {
        public int idapoderado { get; set; }
        public string nombreApoderado { get; set; }
        public string apellidoApoderado { get; set; }
        public string dniApoderado { get; set; }
        public string direccionApoderado { get; set; }
        public string profesionApoderado { get; set; }
        public string telefonoApoderado { get; set; }
        public int idrelacion { get; set; }
        public int idusuario { get; set; }
    
        public virtual Relacion Relacion { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
