//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_SistemaIntranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evaluacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Evaluacion()
        {
            this.Calificacion = new HashSet<Calificacion>();
        }
    
        public int idevaluacion { get; set; }
        public string tituloEvaluacion { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public int horaInicio { get; set; }
        public System.DateTime fechaFin { get; set; }
        public int horaFin { get; set; }
        public string observacionEvaluacion { get; set; }
        public string rutaEvaluacion { get; set; }
        public string estadoEvaluacion { get; set; }
        public int idcurso { get; set; }
        public int idtipo { get; set; }
        public int idgrado_seccion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calificacion> Calificacion { get; set; }
        public virtual Curso Curso { get; set; }
        public virtual Grado_Has_Seccion Grado_Has_Seccion { get; set; }
        public virtual TipoEvaluacion TipoEvaluacion { get; set; }
    }
}
