//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_SistemaIntranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horario
    {
        public int idhorario { get; set; }
        public string diaHorario { get; set; }
        public Nullable<int> horaInicio { get; set; }
        public Nullable<int> horaFin { get; set; }
        public int idseccion { get; set; }
        public int idgrado { get; set; }
        public int idcurso { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual Grado Grado { get; set; }
        public virtual Seccion Seccion { get; set; }
    }
}
