//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_SistemaIntranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol_has_Acceso
    {
        public int id { get; set; }
        public int idrol { get; set; }
        public int idacceso { get; set; }
    
        public virtual Acceso Acceso { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
