//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_SistemaIntranet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int idusuario { get; set; }
        public string nombreUsuario { get; set; }
        public string apellidoUsuario { get; set; }
        public string dniUsuario { get; set; }
        public System.DateTime fechaNacUsuario { get; set; }
        public string direccionUsuario { get; set; }
        public string telefonoUsuario { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public int idrol { get; set; }
        public string rutaImagen { get; set; }
    
        public virtual Rol Rol { get; set; }
    }
}
